Repository Tresjs/cientos, pull requests merged in 2023-12, with the labels that each got.

#306 feat: Stats-gl v2
  package.json
  pnpm-lock.yaml
  src/core/misc/StatsGl.ts
Labels: v4

#310 fix: remove wrapper element on unmounted
  playground/src/pages/misc/HTMLDemo.vue
  src/core/misc/html/HTML.vue
Labels: bug

#308 refactor: remove TweakPane, use Leches
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/CustomShaderMaterialDemo.vue
  docs/guide/misc/use-tweakpane.md
  docs/package.json
  playground/src/pages/abstractions/FBODemo.vue
  playground/src/pages/abstractions/LeviosoDemo.vue
  playground/src/pages/controls/CameraControlsDemo.vue
  playground/src/pages/controls/OrbitControlsDemo.vue
  playground/src/pages/controls/TransformControlsDemo.vue
  playground/src/pages/materials/CustomShaderMaterialDemo.vue
  playground/src/pages/staging/ContactShadowsDemo.vue
  playground/src/pages/staging/PrecipitationDemo.vue
  playground/src/pages/staging/StarsDemo.vue
  pnpm-lock.yaml
  src/core/misc/useTweakPane/index.ts
Labels: v4

#313 feat: remove tweakpane
  package.json
  playground/src/pages/abstractions/Sampler.vue
  pnpm-lock.yaml
  src/core/misc/index.ts
  src/core/misc/useTweakPane/index.ts
  vite.config.ts
Labels: deps, v4
