Repository Tresjs/cientos, pull requests merged in 2023-11, with the labels that each got.

#278 fix: avoid html container to be appended again
  playground/src/pages/misc/Card.vue
  playground/src/pages/misc/HTMLDemo.vue
  src/core/misc/html/HTML.vue
Labels: bug

#293 chore(deps): update to vite v5
  docs/package.json
  package.json
  playground/auto-imports.d.ts
  playground/package.json
  pnpm-lock.yaml
Labels: deps, v4

#286 feat: sampler and useSampler
  .gitignore
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/SamplerDemo.vue
  docs/.vitepress/theme/components/UseSurfaceSamplerDemo.vue
  docs/guide/abstractions/sampler.md
  docs/guide/abstractions/use-surface-sampler.md
  playground/components.d.ts
  playground/src/pages/abstractions/Sampler.vue
  playground/src/pages/abstractions/useSurfaceSampler.vue
  playground/src/router/routes/abstractions.ts
  src/core/abstractions/index.ts
  src/core/abstractions/useSurfaceSampler/component.vue
  src/core/abstractions/useSurfaceSampler/index.ts
Labels: v4
