Repository Tresjs/cientos, pull requests merged in 2023-05, with the labels that each got.

#70 feat: contact shadows
  docs/.vitepress/config.ts
  docs/guide/abstractions/contact-shadows.md
  docs/public/cientos/contact-shadows.png
  playground/components.d.ts
  playground/src/components/ContactShadowsDemo.vue
  playground/src/pages/index.vue
  pnpm-lock.yaml
  src/core/abstractions/ContactShadows.vue
  src/core/abstractions/index.ts
Labels: enhancement, abstraction

#72 feat: 3 enhance orbitcontrols cientos abstraction
  docs/guide/controls/orbit-controls.md
  playground/components.d.ts
  playground/package.json
  playground/src/components/ModelsDemo.vue
  playground/src/components/OrbitControlsDemo.vue
  playground/src/pages/index.vue
  playground/tsconfig.json
  pnpm-lock.yaml
  src/core/controls/OrbitControls.vue
Labels: enhancement

#77 feat: add github form issues
  .github/ISSUE_TEMPLATE/bug.report.yml
  .github/ISSUE_TEMPLATE/feature-request-🪐.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/🐛-bug-report.md
Labels: enhancement, dx

#82 feat: update core 210
  .eslintrc.cjs
  package.json
  playground/.eslintrc-auto-import.json
  playground/auto-imports.d.ts
  playground/package.json
  playground/src/components/TheSmoke.vue
  playground/src/pages/index.vue
  playground/vite.config.ts
  pnpm-lock.yaml
  src/core/abstractions/Smoke.vue
  src/core/shapes/Box.vue
  src/core/shapes/Circle.vue
  src/core/shapes/Cone.vue
  src/core/shapes/Dodecahedron.vue
  src/core/shapes/Icosahedron.vue
  src/core/shapes/Octahedron.vue
  src/core/shapes/Plane.vue
  src/core/shapes/Ring.vue
  src/core/shapes/Sphere.vue
  src/core/shapes/Tetrahedron.vue
  src/core/shapes/Torus.vue
  src/core/shapes/TorusKnot.vue
  src/core/shapes/Tube.vue
  vite.config.ts
Labels: deps

#85 fix: added missing prop target and removed withDefaults
  src/core/controls/OrbitControls.vue
Labels: bug

#87 fix: refactor transform controls with deconstructor
  package.json
  playground/components.d.ts
  playground/package.json
  playground/src/components/TransformControlsDemo.vue
  playground/src/pages/index.vue
  pnpm-lock.yaml
  src/core/controls/OrbitControls.vue
  src/core/controls/TransformControls.vue
Labels: bug, controls

#91 chore: lint warning console
  .eslintrc.cjs
  playground/src/components/ContactShadowsDemo.vue
  playground/src/components/LeviosoDemo.vue
  playground/src/components/ModelsDemo.vue
  playground/src/components/OrbitControlsDemo.vue
  playground/src/components/TheStars.vue
  playground/src/components/WobbleMaterial.vue
  src/core/abstractions/Text3D.vue
Labels: enhancement, dx
