Repository Tresjs/cientos, pull requests merged in 2024-12, with the labels that each got.

#525 feat(MeshDiscardMaterial): add component, playground, docs
  docs/.vitepress/config.ts
  docs/component-list/components.ts
  docs/guide/materials/mesh-discard-material.md
  playground/vue/src/pages/materials/MeshDiscardMaterialDemo.vue
  playground/vue/src/router/routes/materials.ts
  src/core/materials/index.ts
  src/core/materials/meshDiscardMaterial/index.vue
  src/core/materials/meshDiscardMaterial/material.ts
Labels: feature

#527 feat(Billboard): add component, playground, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/BillboardDemo.vue
  docs/component-list/components.ts
  docs/guide/abstractions/billboard.md
  playground/vue/src/pages/abstractions/BillboardDemo.vue
  playground/vue/src/router/routes/abstractions.ts
  src/core/abstractions/Billboard.vue
  src/core/abstractions/index.ts
Labels: feature

#390 feat: edges
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/EdgesDemo.vue
  docs/guide/abstractions/edges.md
  playground/vue/src/pages/abstractions/EdgesDemo.vue
  playground/vue/src/router/routes/abstractions.ts
  src/core/abstractions/Edges.vue
  src/core/abstractions/index.ts
Labels: feature

#554 chore: update deps
  docs/.vitepress/theme/components/EdgesDemo.vue
  docs/guide/abstractions/edges.md
  docs/package.json
  package.json
  playground/vue/package.json
  playground/vue/src/router/routes/abstractions.ts
  pnpm-lock.yaml
  src/core/abstractions/index.ts
Labels: deps

#529 feat(Image): add component, playground, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/ImageDemo.vue
  docs/component-list/components.ts
  docs/guide/abstractions/image.md
  playground/vue/src/pages/abstractions/ImageDemo.vue
  playground/vue/src/router/routes/abstractions.ts
  src/core/abstractions/Image/ImageMaterial.vue
  src/core/abstractions/Image/ImageMaterialImpl.ts
  src/core/abstractions/Image/component.vue
  src/core/abstractions/index.ts
  src/utils/shaderMaterial.ts
Labels: feature, p3-significant

#536 feat(ScreenSpace): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/ScreenSpaceDemo.vue
  docs/component-list/components.ts
  docs/guide/abstractions/screen-space.md
  playground/vue/src/pages/abstractions/ScreenSpaceDemo.vue
  playground/vue/src/router/routes/abstractions.ts
  src/core/abstractions/ScreenSpace.vue
  src/core/abstractions/index.ts
Labels: feature, p3-significant

#535 feat(ScreenSizer): add component, playground, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/ScreenSizerDemo.vue
  docs/guide/abstractions/screen-sizer.md
  playground/vue/src/pages/abstractions/ScreenSizerDemo.vue
  playground/vue/src/router/routes/abstractions.ts
  src/core/abstractions/ScreenSizer.vue
  src/core/abstractions/index.ts
  src/utils/calculateScaleFactor.ts
Labels: feature, p3-significant

#537 feat(CubeCamera): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/CubeCameraDemo.vue
  docs/component-list/components.ts
  docs/guide/abstractions/cube-camera.md
  playground/vue/src/pages/abstractions/CubeCameraDemo.vue
  playground/vue/src/router/routes/abstractions.ts
  src/core/abstractions/CubeCamera/component.vue
  src/core/abstractions/CubeCamera/useCubeCamera.ts
  src/core/abstractions/index.ts
Labels: feature, p3-significant

#540 feat(Grid): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/GridDemo.vue
  docs/component-list/components.ts
  docs/guide/staging/grid.md
  playground/vue/src/pages/staging/GridDemo.vue
  playground/vue/src/router/routes/staging.ts
  src/core/staging/Grid.vue
  src/core/staging/index.ts
Labels: feature, p3-significant

#541 feat(SoftShadows): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/SoftShadowsDemo.vue
  docs/component-list/components.ts
  docs/guide/staging/soft-shadows.md
  playground/vue/src/pages/staging/SoftShadowsDemo.vue
  playground/vue/src/router/routes/staging.ts
  src/core/staging/SoftShadows.vue
  src/core/staging/index.ts
Labels: feature, p3-significant

#544 feat(Align): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/AlignDemo.vue
  docs/component-list/components.ts
  docs/guide/staging/align.md
  playground/vue/src/pages/staging/AlignDemo.vue
  playground/vue/src/router/routes/staging.ts
  src/core/staging/Align.vue
  src/core/staging/index.ts
Labels: feature, p3-significant

#552 feat(Mask): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/MaskDemo.vue
  docs/component-list/components.ts
  docs/guide/abstractions/mask.md
  playground/vue/src/pages/abstractions/MaskDemo.vue
  playground/vue/src/router/routes/abstractions.ts
  pnpm-lock.yaml
  src/core/abstractions/Mask/component.vue
  src/core/abstractions/Mask/useMask.ts
  src/core/abstractions/index.ts
Labels: feature, p3-significant

#543 feat(Helper): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/HelperDemo.vue
  docs/component-list/components.ts
  docs/guide/controls/helper.md
  playground/vue/src/pages/controls/HelperDemo.vue
  playground/vue/src/router/routes/controls.ts
  src/core/controls/Helper/component.vue
  src/core/controls/Helper/useHelper.ts
  src/core/controls/index.ts
Labels: feature

#545 feat(PointMaterial): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/PointMaterialDemo.vue
  docs/component-list/components.ts
  docs/guide/materials/point-material.md
  playground/vue/src/pages/materials/PointMaterialDemo.vue
  playground/vue/src/router/routes/materials.ts
  src/core/materials/index.ts
  src/core/materials/pointMaterial/component.vue
  src/core/materials/pointMaterial/material.ts
Labels: feature

#561 fix(positional-audio): instance properties and fix demo
  docs/.vitepress/theme/components/PositionalAudioDemo.vue
  docs/guide/abstractions/positional-audio.md
  src/core/abstractions/PositionalAudio.vue
Labels: bug, p3-minor-bug

#553 feat(MarchingCubes): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/MarchingCubesDemo.vue
  docs/component-list/components.ts
  docs/guide/abstractions/marching-cubes.md
  playground/vue/src/pages/abstractions/MarchingCubesDemo.vue
  playground/vue/src/router/routes/abstractions.ts
  src/core/abstractions/MarchingCubes/MarchingCube.vue
  src/core/abstractions/MarchingCubes/MarchingCubes.vue
  src/core/abstractions/MarchingCubes/MarchingPlane.vue
  src/core/abstractions/MarchingCubes/const.ts
  src/core/abstractions/index.ts
Labels: feature, p3-significant
