Repository Tresjs/cientos, pull requests merged in 2024-04, with the labels that each got.

#339 feat(app)!: 227 Change the keyboardcontrols implementation
  docs/.vitepress/theme/components/KeyboardControlsDemo.vue
  docs/guide/controls/keyboard-controls.md
  playground/src/pages/controls/KeyboardControls.vue
  playground/src/pages/controls/PointerLockControls.vue
  playground/src/router/routes/controls.ts
  src/core/controls/KeyboardControls.vue
Labels: v4

#370 feat(app): Add holographic material to cientos
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/HolographicMaterialDemo.vue
  docs/guide/materials/holographic-material.md
  playground/src/pages/materials/HolographicMaterialDemo.vue
  playground/src/router/routes/materials.ts
  src/core/materials/holographicMaterial/index.vue
  src/core/materials/holographicMaterial/material.ts
  src/core/materials/index.ts
Labels: feature, p3-significant

#377 fix(MeshReflectionMaterial)!: add features/docs, reorganize
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/MeshReflectionMaterialDemo.vue
  docs/guide/materials/mesh-reflection-material.md
  playground/src/pages/materials/MeshReflectionMaterialDemo.vue
  playground/src/pages/materials/ReflectionMaterial.vue
  playground/src/router/routes/materials.ts
  src/core/materials/meshReflectionMaterial/BlurPass.ts
  src/core/materials/meshReflectionMaterial/ConvolutionMaterial.ts
  src/core/materials/meshReflectionMaterial/index.vue
  src/core/materials/meshReflectionMaterial/material.ts
Labels: feature, v4, breaking-change, p3-significant

#382 feat(app): Add Environment, allowing it to mount sub-components and Lightformer via FBO
  docs/guide/staging/environment.md
  playground/src/pages/staging/EnvironmentDemo.vue
  src/core/staging/index.ts
  src/core/staging/useEnvironment/component.vue
  src/core/staging/useEnvironment/const.ts
  src/core/staging/useEnvironment/envSence.ts
  src/core/staging/useEnvironment/index.ts
  src/core/staging/useEnvironment/lightformer/index.vue
Labels: feature, p2-nice-to-have

#365 feat: 246 positional audio
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/PositionalAudioDemo.vue
  docs/guide/abstractions/positional-audio.md
  docs/public/positional-audio/sketch.jpg
  playground/src/pages/abstractions/PositionalAudio.vue
  playground/src/router/routes/abstractions.ts
  src/core/abstractions/PositionalAudio.vue
  src/core/abstractions/index.ts
Labels: feature, p3-significant
