Repository Tresjs/cientos, pull requests merged in 2024-07, with the labels that each got.

#436 feat: 423 enable on demand render mode usage
  .github/workflows/lint.yml
  playground/components.d.ts
  playground/src/components/GraphPane.vue
  playground/src/composables/state.ts
  playground/src/pages/abstractions/AnimatedSpriteDemo.vue
  playground/src/pages/abstractions/FBODemo.vue
  playground/src/pages/abstractions/PositionalAudioDemo.vue
  playground/src/pages/abstractions/Sampler.vue
  playground/src/pages/abstractions/fbo/FBODemo.vue
  playground/src/pages/abstractions/fbo/index.vue
  playground/src/pages/abstractions/fbo/useFBODemo.vue
  playground/src/pages/abstractions/lensflare/LensflareDemo.vue
  playground/src/pages/abstractions/lensflare/index.vue
  playground/src/pages/controls/KeyboardControlsDemo.vue
  playground/src/pages/controls/OrbitControlsDemo.vue
  playground/src/pages/controls/PointerLockControlsDemo.vue
  playground/src/pages/materials/WobbleMaterialDemo.vue
  playground/src/pages/misc/BakeShadowsDemo.vue
  playground/src/pages/staging/FitDemo.vue
  playground/src/pages/staging/fit/FitDemo.vue
  playground/src/pages/staging/fit/index.vue
  playground/src/router/routes/abstractions.ts
  playground/src/router/routes/controls.ts
  playground/src/router/routes/materials.ts
  playground/src/router/routes/misc.ts
  playground/src/router/routes/staging.ts
  src/composables/useOnDemandInvalidation.ts
  src/core/abstractions/AnimatedSprite/component.vue
  src/core/abstractions/Levioso.vue
  src/core/abstractions/MouseParallax.vue
  src/core/abstractions/Reflector.vue
  src/core/abstractions/Text3D.vue
  src/core/abstractions/useFBO/index.ts
  src/core/abstractions/useSurfaceSampler/component.vue
  src/core/controls/CameraControls.vue
  src/core/controls/KeyboardControls.vue
  src/core/controls/MapControls.vue
  src/core/controls/OrbitControls.vue
  src/core/controls/PointerLockControls.vue
  src/core/controls/ScrollControls.vue
  src/core/controls/TransformControls.vue
  src/core/materials/customShaderMaterial/index.vue
  src/core/materials/holographicMaterial/index.vue
  src/core/materials/meshReflectionMaterial/index.vue
  src/core/materials/meshWobbleMaterial/index.vue
  src/core/staging/Fit.vue
  src/core/staging/Ocean.vue
  src/core/staging/Precipitation.vue
  src/core/staging/Sky.vue
  src/core/staging/Smoke.vue
  src/core/staging/Stars.vue
  src/core/staging/useEnvironment/component.vue
  src/core/staging/useEnvironment/index.ts
Labels: feature, dx, performance, p3-significant

#448 fix(types): usegltf type issue
  package.json
  pnpm-lock.yaml
  src/core/loaders/useGLTF/index.ts
Labels: p3-minor-bug, types

#449 fix: reimplement ContactShadows for v4
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/ContactShadowDemo.vue
  docs/.vitepress/theme/components/ContactShadowsDemo.vue
  docs/component-list/components.ts
  docs/guide/staging/contact-shadows.md
  package.json
  playground/src/pages/staging/ContactShadowsDemo.vue
  src/core/staging/ContactShadows.vue
Labels: p4-important-bug

#446 feat(Sparkles): invalidate on update
  src/core/staging/Sparkles/component.vue
Labels: v4

#452 chore: remove on demand composable
  src/composables/useOnDemandInvalidation.ts
  src/core/abstractions/Levioso.vue
  src/core/abstractions/MouseParallax.vue
  src/core/abstractions/Reflector.vue
  src/core/abstractions/Text3D.vue
  src/core/abstractions/useFBO/index.ts
  src/core/abstractions/useSurfaceSampler/component.vue
  src/core/controls/CameraControls.vue
  src/core/controls/KeyboardControls.vue
  src/core/controls/MapControls.vue
  src/core/controls/OrbitControls.vue
  src/core/controls/PointerLockControls.vue
  src/core/controls/ScrollControls.vue
  src/core/controls/TransformControls.vue
  src/core/staging/Fit.vue
  src/core/staging/Ocean.vue
  src/core/staging/Precipitation.vue
  src/core/staging/Sky.vue
  src/core/staging/Smoke.vue
Labels: p1-chore
