Repository Tresjs/cientos, pull requests merged in 2025-01, with the labels that each got.

#574 fix(KeyboardControls): support non-qwerty keyboards (#573)
  docs/guide/controls/keyboard-controls.md
  src/core/controls/KeyboardControls.vue
Labels: bug, p3-minor-bug

#546 feat(CubicBezierLine): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/CubicBezierLineDemo.vue
  docs/component-list/components.ts
  docs/guide/shapes/cubic-bezier-line.md
  playground/vue/src/pages/shapes/CubicBezierLineDemo.vue
  playground/vue/src/router/routes/shapes.ts
  src/core/shapes/CubicBezierLine.vue
  src/core/shapes/index.ts
Labels: feature

#548 feat(QuadraticBezierLine): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/QuadraticBezierLineDemo.vue
  docs/component-list/components.ts
  docs/guide/shapes/quadratic-bezier-line.md
  playground/vue/src/pages/shapes/QuadraticBezierLineDemo.vue
  playground/vue/src/router/routes/shapes.ts
  src/core/shapes/QuadraticBezierLine.vue
  src/core/shapes/index.ts
Labels: feature, p3-significant

#558 feat(AccumulativeShadows): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/AccumulativeShadowsDemo.vue
  docs/component-list/components.ts
  docs/guide/staging/accumulative-shadows.md
  docs/guide/staging/randomized-lights.md
  playground/vue/src/pages/staging/AccumulativeShadowsDemo.vue
  playground/vue/src/router/routes/staging.ts
  src/core/staging/AccumulativeShadows/ProgressiveLightMap.ts
  src/core/staging/AccumulativeShadows/SoftShadowMaterial.ts
  src/core/staging/AccumulativeShadows/component.vue
  src/core/staging/RandomizedLights/RandomizedLights.ts
  src/core/staging/RandomizedLights/component.vue
  src/core/staging/index.ts
Labels: feature, p3-significant

#568 feat(Bounds): add component, demo, docs (#408)
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/BoundsDemo.vue
  docs/component-list/components.ts
  docs/guide/staging/bounds.md
  playground/vue/src/pages/staging/BoundsDemo.vue
  playground/vue/src/router/routes/staging.ts
  src/core/staging/Bounds/Bounds.ts
  src/core/staging/Bounds/component.vue
  src/core/staging/index.ts
Labels: feature, p3-significant

#549 feat(CircleShadow): add component, demo, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/CircleShadowDemo.vue
  docs/component-list/components.ts
  docs/guide/staging/circle-shadow.md
  playground/vue/src/pages/staging/CircleShadowDemo.vue
  playground/vue/src/router/routes/staging.ts
  src/core/staging/CircleShadow.vue
  src/core/staging/index.ts
Labels: feature, p3-significant

#524 feat(LOD): add component, playground, docs
  docs/.vitepress/config.ts
  docs/.vitepress/theme/components/LODDemo.vue
  docs/component-list/components.ts
  docs/guide/misc/lod.md
  playground/vue/src/pages/misc/LODDemo.vue
  playground/vue/src/router/routes/misc.ts
  src/core/misc/LOD.vue
  src/core/misc/index.ts
Labels: feature, p3-significant

#550 feat(useIntersect): add function, demo, docs
  docs/.vitepress/config.ts
  docs/component-list/components.ts
  docs/guide/misc/use-intersect.md
  playground/vue/src/pages/misc/useIntersect/TheExperience.vue
  playground/vue/src/pages/misc/useIntersect/index.vue
  playground/vue/src/router/routes/misc.ts
  src/core/misc/index.ts
  src/core/misc/useIntersect.ts
Labels: feature

#584 fix: 581 environment lightformers are not working
  playground/vue/src/pages/staging/environment/EnvironmentDemo.vue
  playground/vue/src/pages/staging/environment/Lightformers.vue
  playground/vue/src/router/routes/staging.ts
  src/core/staging/useEnvironment/EnvironmentScene.ts
  src/core/staging/useEnvironment/component.vue
  src/core/staging/useEnvironment/lightformer/index.vue
Labels: bug, p4-important-bug
